# Copyright © 2026 星云云络科技 | NebulaDex 项目 | 基于 MIT 开源协议发布
# Copyright © 2026 Xingyun Cloud Tech | NebulaDex Project | Released under the MIT License

name: NebulaDex

options:
  bundleIdPrefix: com.xingyun
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: NebulaDex
    MARKETING_VERSION: "0.2.0"
    CURRENT_PROJECT_VERSION: "2"
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    CLANG_ENABLE_MODULES: YES
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  NebulaDex:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xingyun.NebulaDex
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Entitlements/NebulaDex.entitlements
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_OBJC_BRIDGING_HEADER: Sources/framework/NebulaDex-Bridging-Header.h
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
    dependencies:
      - sdk: libsqlite3.tbd
      - sdk: libz.tbd

schemes:
  NebulaDex:
    build:
      targets:
        NebulaDex: all
    run:
      config: Release
    archive:
      config: Release
